# Training Notes
# smaller version using 512d tokens / 8 + 4 layers like from paper
# about 71.8M params
# --> train at 128x128 resolution
# new custom generated dataset

# Total parameters:        71,771,535
# Trainable parameters:    71,771,523
# Transformer params:      33,570,822
# View Transformer params: 31,314,313
#         Out DPT params:          10,226,563

model:
  latent_dim: 512 # reduced
  num_layers: 8 # reduced
  num_heads: 4 # reduced
  dim_feedforward: 2048 # reduced
  num_register_tokens: 16
  dropout: 0.0
  activation: swiglu
  norm_type: rms_norm
  norm_first: True
  view_indep_qk_norm: True
  qk_norm: True
  bias: False
  pe_type: rope
  rope_type: triangle
  rope_double_max_freq: False
  vertex_pe_num_freqs: 12
  use_vn_encoder: True
  vn_pe_num_freqs: 6
  vn_encoder_norm_type: rms_norm
  texture_encode_patch_size: 32
  texture_channels: 13
  texture_encoder_norm_type: rms_norm
  view_transformer_latent_dim: 512 # reduced
  view_transformer_ffn_hidden_dim: 2048 # reduced
  view_transformer_n_heads: 4 # reduced
  view_transformer_n_layers: 4 # reduced
  view_transformer_include_self_attn: True
  view_transformer_use_swin_attn: False
  vdir_pe_type: nerf
  vdir_num_freqs: 0
  patch_size: 8
  include_alpha: False
  use_dpt_decoder: True
  dpt_features: 128
  dpt_out_channels: [96, 192, 384, 768] # keep as before...?
  turn_to_cam_coord: True
  use_ldr: False

training:
#  According to the linear scaling rule, 
#  a 4x increase in batch size usually allows for a 4x increase in learning rate
  global_batch_size: 128 #192 # 24 * 8
  learning_rate: 1.0e-4 # RF paper suggests 1e-4 
  weight_decay: 0.01  # applied to weight matrices only; biases/norms exempt
  clip_grad_norm: 1.0 # Added to prevent model outputting negatives and causing dead gradients
  min_learning_rate: 1.0e-6
  num_steps: 75000 # 
  warmup_steps: 4000
  save_interval_steps: 2500  # for visualization
  checkpoint_interval_steps: 15000  # for saving model checkpoint 
  log_interval_steps: 25
  image_res: 128
  data_dir: 
      - "/dev/shm/datasets/dataset_uniform" # all 100k  
  dataset_split_ratio: 0.99
  log_dir: "training/logs/dataset_uniform_full"
  run_name: "params71M_renderformer_d512" # Optional string tag for log dir name
  # max_dataset_size: 10   # Optional max samples for dataset
  # shuffle_data: true # defaults to true
  # shuffle_data_seed: 42
  primary_loss: 'mae' # 'mse'
  lpips_backbone: 'alex' # 'vgg'
  lpips_loss_weighting: 0.05
  use_amp: True
  use_compile: False
  package_model: True
  num_workers: 30
  prefetch_factor: 12
  cache_strategy: 'disk'